# Generated by Django 3.2.9 on 2021-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='relocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
