# Generated by Django 3.2.9 on 2021-12-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_station_relocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='network',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
