# Generated by Django 3.2.9 on 2022-03-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_station_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationvariable',
            name='test_range_max',
        ),
        migrations.RemoveField(
            model_name='stationvariable',
            name='test_range_min',
        ),
        migrations.AddField(
            model_name='station',
            name='reference_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.station'),
        ),
    ]
