# Generated by Django 3.2.9 on 2022-03-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_station_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RenameField(
            'Station', 
            'country', 
            'remaks'
        ),
        migrations.AddField(
            model_name='country',
            name='notation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='wmoprogram',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmoprogram',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmoregion',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmostationtype',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        
    ]
