# Generated by Django 3.2.9 on 2022-03-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_auto_20220312_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='remaks',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='station',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
