# Generated by Django 3.2.9 on 2022-03-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_auto_20220320_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='reference_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.station'),
        ),
    ]
