# Generated by Django 3.2.9 on 2022-03-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0005_alter_station_reference_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationvariable',
            name='test_step_max',
        ),
        migrations.RemoveField(
            model_name='stationvariable',
            name='test_step_min',
        ),
    ]
