# Generated by Django 3.2.9 on 2022-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0006_auto_20220330_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmoprogram',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmoregion',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmoregion',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wmostationtype',
            name='notation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
