# Generated by Django 3.2.9 on 2022-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0009_auto_20220411_1758'),
    ]

    operations = [
            migrations.RenameField(model_name='station', old_name='country', new_name='remarks'),
            migrations.RenameField(model_name='station', old_name='country_link', new_name='country'),
        
    ]
