# Generated by Django 3.2.9 on 2022-04-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0010_transfer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
