# Generated by Django 3.2.9 on 2022-04-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0011_auto_20220411_2305'),
    ]

    operations = [
        migrations.RenameField(model_name='country', old_name='code', new_name='notation'),
    ]
