# Generated by Django 3.2.9 on 2022-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0012_rename_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmoprogram',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
