# Generated by Django 3.2.9 on 2022-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0013_alter_wmoprogram_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationvariable',
            name='test_persistence_window',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
