# Generated by Django 3.2.9 on 2022-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0014_auto_20220528_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='persistence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='persistence_hourly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='range_max_hourly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='range_min_hourly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='step_hourly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
