# Generated by Django 3.2.9 on 2022-08-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import wx.models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0016_auto_20220623_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='persistence_window',
            field=models.IntegerField(blank=True, null=True, verbose_name='Persistence Window (in hours)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence_window_hourly',
            field=models.IntegerField(blank=True, null=True, verbose_name='Persistence Window hourly (in hours)'),
        ),
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('cron_schedule', models.CharField(default='0 0 * * *', max_length=64, validators=[wx.models.BackupTask.cron_validator])),
                ('file_name', models.CharField(max_length=1024)),
                ('retention', models.IntegerField(verbose_name='Retention (in days)')),
                ('remote_folder', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField()),
                ('ftp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.ftpserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=1024)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.FloatField(blank=True, null=True, verbose_name='File Size (MB)')),
                ('backup_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.backuptask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
