# Generated by Django 3.2.13 on 2022-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0018_auto_20221104_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdatafile',
            name='is_highfrequency_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stationfileingestion',
            name='is_highfrequency_data',
            field=models.BooleanField(default=False),
        ),
    ]
