# Generated by Django 3.2.13 on 2022-11-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0019_auto_20221109_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HightFrequencyData',
            new_name='HighFrequencyData',
        ),
    ]
