# Generated by Django 3.2.13 on 2022-11-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0020_rename_hightfrequencydata_highfrequencydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFSummaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.station')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.variable')),
            ],
            options={
                'unique_together': {('station', 'variable', 'start_datetime', 'end_datetime')},
            },
        ),
    ]
