# Generated by Django 3.2.13 on 2023-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0022_maintenancereport_maintenancereportstationcomponent_stationcomponent_stationprofilecomponent_technic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Draft'), ('P', 'Published'), ('-', 'Deleted')], default='D', max_length=1),
        ),
    ]
