# Generated by Django 3.2.13 on 2023-05-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0023_auto_20230428_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='is_synoptic_station',
            field=models.BooleanField(default=False),
        ),
    ]
