# Generated by Django 3.2.13 on 2023-06-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0024_equipment_equipmenttype_foundingsource_manufacturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoundingSource',
            new_name='FundingSource',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='founding_source',
            new_name='funding_source',
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('F', 'Fully Functional'), ('P', 'Partially Functional'), ('N', 'Not Functional')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_deploy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.station'),
        ),
    ]
