# Generated by Django 3.2.13 on 2023-07-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0026_auto_20230705_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='classification',
            field=models.CharField(choices=[('F', 'Fully Functional'), ('P', 'Partially Functional'), ('N', 'Not Functional')], default='F', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='old_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_equipment', to='wx.equipment'),
        ),
    ]
