# Generated by Django 3.2.13 on 2024-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0029_auto_20240928_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='synop_code',
            new_name='synoptic_code',
        ),
        migrations.AddField(
            model_name='station',
            name='synoptic_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
