# Generated by Django 3.2.13 on 2024-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0031_variable_synoptic_code_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='international_station',
            new_name='international_exchange',
        ),
        migrations.AlterField(
            model_name='station',
            name='is_automatic',
            field=models.BooleanField(default=True),
        ),
    ]
